app:
  name: employee-service
  description: service related to users.

server:
  port: 8083
  servlet:
    context-path: /api/employee-service

spring:
  redis:
    host: localhost
    port: 6379

booking.service.url: http://localhost:8082/api/booking-service/
