apiVersion: v1
kind: Service
metadata:
  labels:
    app: opendesk-web-ui
  name: opendesk-web-ui
  namespace: kanwalnainsingh
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: opendesk-web-ui
  type: ClusterIP
