apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: OpenDeskRoleBinding
  namespace: kanwalnainsingh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: OpenDeskRole
subjects:
- kind: ServiceAccount
  name: default
  namespace: kanwalnainsingh
