# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ Initial_Planning, main ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ Initial_Planning, main ]
    paths-ignore:
    - 'docs/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
          
      - name: Maven Package Organisation Service
        run: | 
          cd code_base/micro-services/organisation-service/
          mvn -B clean package -DskipTests
      - name: Maven Verify Organisation Service
        run: |
           cd code_base/micro-services/organisation-service/
           mvn -B clean verify
           
      - name: Maven Package Booking Service
        run: | 
          cd code_base/micro-services/booking-service/
          mvn -B clean package -DskipTests
      - name: Maven Verify Booking Service
        run: |
           cd code_base/micro-services/booking-service/
           mvn -B clean verify
      - name: Maven Package Employee Service
        run: | 
          cd code_base/micro-services/employee-service/
          mvn -B clean package -DskipTests
      - name: Maven Verify Employee Service
        run: |
           cd code_base/micro-services/employee-service/
           mvn -B clean verify
           
      - name: Maven Package Desk Service
        run: | 
          cd code_base/micro-services/desk-service/
          mvn -B clean package -DskipTests
      - name: Maven Verify Desk Service
        run: |
           cd code_base/micro-services/desk-service/
           mvn -B clean verify
                
